# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GleanTennessee' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GleanTennessee

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Messaging'
	pod 'Firebase/Functions'
  pod 'Firebase/RemoteConfig'

end
